version: '3.8'

services:
  maxiter:
    build:
      context: .
      dockerfile: Dockerfile
    image: maxiter-php/maxiter:latest
    container_name: maxiter_container
    ports:
      - "7000:80"
    volumes:
      - .:/var/www/html